
export const events = [
    {
      id: 1,
      name: "Music Festival",
      date: "2024-11-01",
      location: "New York",
      description: "Enjoy live music from top artists.",
      image: "/assets/musicFestival.jpeg",
    },
    {
      id: 2,
      name: "Art Exhibit",
      date: "2024-11-05",
      location: "Los Angeles",
      description: "Explore contemporary art pieces.",
      image: "/assets/artExhibit.jpeg",
    },
    {
      id: 3,
      name: "Food Carnival",
      date: "2024-11-10",
      location: "Chicago",
      description: "Taste the best dishes from around the world.",
      image: "/assets/foodCarnival.jpeg",
    },
    {
      id: 4,
      name: "Tech Conference",
      date: "2024-11-12",
      location: "San Francisco",
      description: "Join the tech community to discuss emerging trends.",
      image: "/assets/techConference.jpeg",
    },
    {
      id: 5,
      name: "Yoga Workshop",
      date: "2024-11-15",
      location: "Austin",
      description: "Learn and practice yoga techniques.",
      image: "/assets/yogaWorkshop.jpeg",
    },
    {
      id: 6,
      name: "Film Screening",
      date: "2024-11-18",
      location: "Seattle",
      description: "Enjoy a screening of classic films.",
      image: "/assets/film.jpeg",
    },
    {
      id: 7,
      name: "Book Fair",
      date: "2024-11-20",
      location: "India",
      description: "Meet authors and explore new releases.",
      image: "/assets/bookFair.jpeg",
    },
    {
      id: 8,
      name: "Stand-up Comedy",
      date: "2024-11-22",
      location: "Miami",
      description: "Laugh out loud with top comedians.",
      image: "/assets/standup.jpeg",
    },
    {
      id: 9,
      name: "Photography Workshop",
      date: "2024-11-25",
      location: "Portland",
      description: "Improve your photography skills.",
      image: "/assets/photography.jpeg",
    },
    {
      id: 10,
      name: "Craft Fair",
      date: "2024-11-28",
      location: "Philadelphia",
      description: "Shop for handmade crafts and unique gifts.",
      image: "/assets/craft.jpeg",
    },
    
  ];
  
